/**
 * Generated by XDK LIVE.
 * @date 2018-06-29 23:25:09
 */


#ifndef CONNECTIVITYWLAN_WLAN_H
#define CONNECTIVITYWLAN_WLAN_H

#include <BCDS_Retcode.h>


/**
 * Sets up the WLAN.
 */
Retcode_T ConnectivityWLANMywlan_Setup(void);

/**
 * Enables the WLAN sensor.
 */
Retcode_T ConnectivityWLANMywlan_Enable(void);



#endif
