/**
 * Generated by XDK LIVE.
 * @date 2018-06-29 23:25:09
 */


#ifndef CONNECTIVITYMQTT_MQTT_H
#define CONNECTIVITYMQTT_MQTT_H

#include <BCDS_Retcode.h>


/**
 * Sets up the MQTT.
 */
Retcode_T ConnectivityMQTTMqtt_test_Setup(void);

/**
 * Enables the MQTT sensor.
 */
Retcode_T ConnectivityMQTTMqtt_test_Enable(void);

/**
 * Provides read access to data_publish.
 */
Retcode_T ConnectivityMQTTMqtt_test_Data_publish_Read(char** result);

/**
 * Provides write access to data_publish.
 */
Retcode_T ConnectivityMQTTMqtt_test_Data_publish_Write(char** result);


#endif
