/**
 * Generated by XDK LIVE.
 * @date 2018-06-29 23:25:09
 */


#ifndef CONNECTIVITYLED_LED_H
#define CONNECTIVITYLED_LED_H

#include <stdbool.h>
#include <BCDS_Retcode.h>


/**
 * Sets up the LED.
 */
Retcode_T ConnectivityLEDHmi_Setup(void);

/**
 * Enables the LED sensor.
 */
Retcode_T ConnectivityLEDHmi_Enable(void);

/**
 * Provides read access to led_test.
 */
Retcode_T ConnectivityLEDHmi_Led_test_Read(bool* result);

/**
 * Provides write access to led_test.
 */
Retcode_T ConnectivityLEDHmi_Led_test_Write(bool* result);


#endif
