/**
 * Generated by XDK LIVE.
 * @date 2018-06-29 23:25:09
 */


#ifndef SENSORBUTTON_ONE_BUTTON_ONE_H
#define SENSORBUTTON_ONE_BUTTON_ONE_H

#include <BCDS_Retcode.h>


/**
 * Sets up the button_one.
 */
Retcode_T SensorButton_one_Setup(void);

/**
 * Enables the button_one sensor.
 */
Retcode_T SensorButton_one_Enable(void);



#endif
