/**
 * Generated by XDK LIVE.
 * @date 2018-06-29 23:25:09
 */


#ifndef SENSORBUTTON_TWO_BUTTON_TWO_H
#define SENSORBUTTON_TWO_BUTTON_TWO_H

#include <BCDS_Retcode.h>


/**
 * Sets up the button_two.
 */
Retcode_T SensorButton_two_Setup(void);

/**
 * Enables the button_two sensor.
 */
Retcode_T SensorButton_two_Enable(void);



#endif
