/**
 * Generated by XDK LIVE.
 * @date 2018-06-29 23:25:09
 */


#ifndef XDKLIVE_EVENTS_H
#define XDKLIVE_EVENTS_H

#include <BCDS_Retcode.h>
#include <BCDS_CmdProcessor.h>
#include <BCDS_Basics.h>


extern CmdProcessor_T XdkLive_EventQueue;

Retcode_T HandleEveryButton_onePressed1(void* userParameter1, uint32_t userParameter2);

Retcode_T HandleEveryButton_twoPressed1(void* userParameter1, uint32_t userParameter2);


#endif
